#version 150 core
#line 2 0


#line 1 1

layout(std140) uniform uboMatrix3D
{
    mat4 mvp;
    mat4 mv;
    mat4 view;
    mat4 vp;
    mat4 p;
    mat4 normal;
    mat4 mv_inv;
    mat4 proj_inv;
    mat4 mvp_inv;
} in_matrix_3D;

layout(std140) uniform uboMatrix2D
{
    mat4 mvp;
    mat4 p3DOrtho;
    mat4 mv3DOrtho;
} in_matrix_2D;

layout(std140) uniform uboMatrixShadow
{
    mat4 shadow_split_mvp[4];
    vec4 shadow_split_depth;
} in_matrix_shadow;

layout(std140) uniform uboSceneData
{
    vec4 cameraPosition;
    vec4 framePos;
    vec4 viewport;
    vec4 pxoffset;
    vec4 prevCameraPosition;
    vec4 sceneSettings;
} in_scene;

#define FRAME_TIME in_scene.framePos.w
#define CAMERA_POS in_scene.cameraPosition.xyz
#define PREV_CAMERA_POS in_scene.prevCameraPosition.xyz
#define RENDER_OFFSET in_scene.framePos.xyz
#define PX_OFFSET in_scene.pxoffset
#line 1 2
const float A = 0.15;
const float B = 0.50;
const float C = 0.10;
const float D = 0.20;
const float E = 0.02;
const float F = 0.30;
const float W = 11.2;

#define SRGB_TEXTURES

void srgb(inout float v)
{
    v = clamp(v, 0.0, 1.0);
    float K0 = 0.03928;
    float a = 0.055;
    float phi = 12.92;
    float gamma = 2.4;
    v = v <= K0 / phi ? v * phi : (1.0 + a) * pow(v, 1.0 / gamma) - a;
}
void linear(inout float v)
{
    v = clamp(v, 0.0, 1.0);
    float K0 = 0.03928;
    float a = 0.055;
    float phi = 12.92;
    float gamma = 2.4;
    v = v <= K0 ? v / phi : pow((v + a) / (1.0 + a), gamma);
}
void linearizeInput(inout vec3 srgb)
{
    #ifndef SRGB_TEXTURES
    linear(srgb.x);
    linear(srgb.y);
    linear(srgb.z);
    #endif
}

void srgbToLin(inout vec3 srgb) {
    linear(srgb.x);
    linear(srgb.y);
    linear(srgb.z);
}
void linToSrgb(inout vec3 linear) {
    srgb(linear.x);
    srgb(linear.y);
    srgb(linear.z);
}

vec3 Uncharted2Tonemap(vec3 x)
{
    // http://www.gdcvault.com/play/1012459/Uncharted_2__HDR_Lighting
    // http://filmicgames.com/archives/75 - the coefficients are from here
    return ((x*(A*x+C*B)+D*E)/(x*(A*x+B)+D*F))-E/F; // E/F = Toe Angle
}

#define MAX_COLOR_RANGE 2.0//TONEMAP   
vec3 Uncharted2Tonemap2(vec3 x) {
float A2 = .8;    //brightness multiplier
float B2 = 0.37;   //black level (lower means darker and more constrasted, higher make the image whiter and less constrasted)
float C2 = 0.1;    //constrast level 
  float D2 = 0.2;    
  float E2 = 0.02;
  float F2 = 0.3;
  float W2 = MAX_COLOR_RANGE;
  return ((x*(A2*x+C2*B2)+D2*E2)/(x*(A2*x+B2)+D2*F2))-E2/F2;
}


vec3 ToneMap( in vec3 texColor, float exposure)
{

  vec3 curr = Uncharted2Tonemap2(exposure*texColor);
  
  vec3 whiteScale = 1.0f/Uncharted2Tonemap2(vec3(MAX_COLOR_RANGE));
 vec3 color = curr*whiteScale;
   // vec3 curr = Uncharted2Tonemap(exposure*texColor);

   // vec3 whiteScale = 1.0f/Uncharted2Tonemap(vec3(W));
   // vec3 color = curr*whiteScale;

   // vec3 retColor = pow(color,vec3(1/2.2));
   linToSrgb(color);
   return color;
}
#line 1 3

#define FRAME_TIME_DITHER (in_scene.framePos.w*20.0)
#define SS_DITHER (in_scene.sceneSettings.x)
vec3 dither8BitSS()
{

    vec3 vDither = vec3(dot(vec2(131.0, 312.0), gl_FragCoord.xy + FRAME_TIME_DITHER));
    return SS_DITHER*((fract(vDither.rgb / vec3(103.0, 71.0, 97.0)) - vec3(0.5, 0.5, 0.5)) / 255.0);
}



float dither8Bit( vec2 n )
{
	float t = fract( FRAME_TIME_DITHER );
	float nrnd0 = fract(sin(dot(( n + 0.07*t ).xy, vec2(12.9898, 78.233)))* 43758.5453);

    // Convert uniform distribution into triangle-shaped distribution.
    float orig = nrnd0*2.0-1.0;
    nrnd0 = orig*inversesqrt(abs(orig));
    nrnd0 = max(-1.0,nrnd0); // Nerf the NaN generated by 0*rsqrt(0). Thanks @FioraAeterna!
    nrnd0 = nrnd0-sign(orig)+0.5;
    
    // convert to [0,1] for histogram.
    // return (nrnd0+0.5) * 0.5;

    // Result is range [-0.5,1.5] which is
    // useful for actual dithering.
    return nrnd0/255.0;
}
#line 7 0

uniform sampler2D texColor;
#ifdef DO_AUTOEXPOSURE
uniform sampler2D texLum;
const float constexposure = 130;
#else
uniform float constexposure;
#endif


in vec2 pass_texcoord;

out vec4 out_Color;
void main(void) {
	vec4 tex = texture(texColor, pass_texcoord.st, 0);
#ifdef DO_AUTOEXPOSURE
	float brightness = 1-pow(1-texelFetch(texLum, ivec2(0,0), 0).r, 1.4);
	float fDyn = 0.7;
	float autoExposure = ((brightness-fDyn)) * -constexposure;
	autoExposure = constexposure*(1.0-fDyn) + autoExposure;
	autoExposure = clamp(autoExposure, 10, 160);
	vec3 toneMapped = ToneMap(tex.rgb, autoExposure);
#else 
	vec3 toneMapped = ToneMap(tex.rgb, constexposure);
#endif
	out_Color = vec4(toneMapped+dither8BitSS(), 1);
}
